// <auto-generated />
using System;
using CREDITProcessament.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CREDITProcessament.Presentation.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20210303193608_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CREDITProcessament.Data.Models.ProcessamentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserCPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("UserCPF")
                        .IsUnique();

                    b.ToTable("Tbl_Processament");
                });

            modelBuilder.Entity("CREDITProcessament.Data.Models.UserModel", b =>
                {
                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("CPF");

                    b.ToTable("Tbl_User");
                });

            modelBuilder.Entity("CREDITProcessament.Data.Models.ProcessamentModel", b =>
                {
                    b.HasOne("CREDITProcessament.Data.Models.UserModel", null)
                        .WithOne("Processament")
                        .HasForeignKey("CREDITProcessament.Data.Models.ProcessamentModel", "UserCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CREDITProcessament.Data.Models.UserModel", b =>
                {
                    b.Navigation("Processament");
                });
#pragma warning restore 612, 618
        }
    }
}
